name: OpenWrt FriendlyARM NanoPi R6S

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0/12 * * 2-6"

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  check:
    outputs:
      latest: ${{ steps.latest.outputs.is_latest }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4
      - name: Set Environment Variable
        run: |
          OPENWRT_VERSION=`./latest-imagebuilder-version.sh rockchip armv8 .`
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - id: latest
        name: Check Published Version
        run: |
          PUBLISHED_VERSION=`curl 'https://downloads.hackinggate.com' | grep 'nanopi-r6s' | grep -E -o ${OPENWRT_VERSION} | tail -1`
          echo "${OPENWRT_VERSION} is latest"
          if [[ "$OPENWRT_VERSION" == "$PUBLISHED_VERSION" ]]; then
            echo "${OPENWRT_VERSION} is published for nanopi-r6s"
            echo "::set-output name=is_latest::true"
          else
            echo "${OPENWRT_VERSION} is NOT published for nanopi-r6s"
          fi
  build:
    needs: check
    if: ${{ needs.check.outputs.latest != 'true' || github.event_name != 'schedule' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        major_version: [v]
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4
      - name: Set Environment Variable
        run: |
          OPENWRT_VERSION=`./latest-imagebuilder-version.sh rockchip armv8 ${{ matrix.major_version }}`
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget
      - name: Build NanoPi R6S with imagebuilder
        run: ./nanopi-r6s-openwrt-imagebuilder-build.sh
      - name: Checkout gh-pages
        run : |
          git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch origin gh-pages
          git checkout gh-pages
      - name: Override Files
        run: |
          IMAGE_PREFIX=`cat openwrt-imagebuilder-${OPENWRT_VERSION}-rockchip-armv8.Linux-x86_64/bin/targets/rockchip/armv8/profiles.json | jq '.["profiles"]' | jq 'map(.)' | jq -r '.[] | select(.id == "friendlyarm_nanopi-r6s") | .image_prefix'`
          rm -rf ${IMAGE_PREFIX}
          mv openwrt-imagebuilder-${OPENWRT_VERSION}-rockchip-armv8.Linux-x86_64/bin/targets/rockchip/armv8 ${IMAGE_PREFIX}
          rm -rf openwrt-imagebuilder-*
      - name: Generate gh-pages
        run: |
          git checkout - -- generate-page.sh
          ./generate-page.sh
          rm generate-page.sh
      - name: Tree
        run: | 
          sudo apt install tree
          tree
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: .
          clean: true
          dry-run: ${{ github.event_name == 'pull_request' }}
